name: interview_note_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  awesome_dialog: ^3.1.0
  botion_flutter_plugin: ^0.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  flutter_staggered_grid_view: ^0.7.0
  # google_fonts: ^6.1.0
  hive: ^2.2.3
  hydrated_bloc: ^9.1.2
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
